marcas_modelos = {
    "Toyota": [
        "Corolla", "Corolla Cross", "Corolla Hybrid", "Corolla Sedan", "Corolla Hatchback", "Corolla LE", "Corolla SE", "Corolla XLE", "Corolla XSE",
        "Camry", "Camry Hybrid", "Camry LE", "Camry SE", "Camry XLE", "Camry XSE", "Camry TRD",
        "Hilux", "Hilux 4x4", "Hilux Diesel", "Hilux Double Cab", "Hilux TRD",
        "RAV4", "RAV4 Hybrid", "RAV4 Prime", "RAV4 LE", "RAV4 XLE", "RAV4 Adventure", "RAV4 TRD Off-Road", "RAV4 Limited",
        "Yaris", "Yaris Sedan", "Yaris Hatchback", "Yaris Cross", "Yaris GR",
        "Tundra", "Tundra TRD", "Tundra Limited", "Tundra Platinum", "Tundra 1794 Edition", "Tundra Hybrid",
        "Tacoma", "Tacoma TRD", "Tacoma SR", "Tacoma SR5", "Tacoma TRD Sport", "Tacoma TRD Off-Road", "Tacoma Limited",
        "Land Cruiser", "Land Cruiser Prado", "Land Cruiser 300", "Land Cruiser 200", "Land Cruiser GR Sport",
        "Prius", "Prius Prime", "Prius C", "Prius V", "Prius Hybrid", "Prius Plug-in",
        "Avanza", "C-HR", "C-HR Hybrid", "Sequoia", "Sequoia TRD", "Sequoia Limited", "Sequoia Platinum",
        "Sienna", "Sienna Hybrid", "Sienna LE", "Sienna XLE", "Sienna Limited",
        "Venza", "Venza LE", "Venza XLE", "Venza Limited",
        "4Runner", "4Runner TRD", "4Runner SR5", "4Runner Limited", "4Runner TRD Pro", "4Runner TRD Off-Road",
        "Highlander", "Highlander Hybrid", "Highlander LE", "Highlander XLE", "Highlander Limited", "Highlander Platinum",
        "bZ4X", "Mirai", "Crown", "GR86", "GR Supra"
    ],
    "Honda": [
        "Civic", "Civic Sedan", "Civic Hatchback", "Civic Type R", "Civic Si", "Civic Hybrid", "Civic LX", "Civic EX", "Civic Sport", "Civic Touring",
        "Accord", "Accord Hybrid", "Accord Sport", "Accord EX", "Accord LX", "Accord Touring", "Accord Sedan",
        "CR-V", "CR-V Hybrid", "CR-V LX", "CR-V EX", "CR-V EX-L", "CR-V Touring", "CR-V Black Edition",
        "Fit", "Fit LX", "Fit Sport", "Fit EX", "Fit EX-L",
        "HR-V", "HR-V LX", "HR-V Sport", "HR-V EX", "HR-V EX-L", "HR-V Touring",
        "Pilot", "Pilot LX", "Pilot EX", "Pilot Touring", "Pilot Elite", "Pilot Black Edition", "Pilot TrailSport",
        "City", "City Sedan", "City Hatchback",
        "Jazz", "Jazz Crosstar", "Jazz Hybrid",
        "Odyssey", "Odyssey LX", "Odyssey EX", "Odyssey EX-L", "Odyssey Touring", "Odyssey Elite",
        "Ridgeline", "Ridgeline Sport", "Ridgeline RTL", "Ridgeline RTL-E", "Ridgeline Black Edition",
        "Insight", "Insight Touring", "Insight Hybrid",
        "Passport", "Passport Sport", "Passport EX-L", "Passport Touring", "Passport Elite", "Passport TrailSport",
        "WR-V", "BR-V", "Clarity", "Prologue", "e:Ny1", "ZR-V"
    ],
    "Nissan": [
        "Sentra", "Sentra S", "Sentra SV", "Sentra SR", "Sentra NISMO",
        "Altima", "Altima S", "Altima SV", "Altima SR", "Altima SL", "Altima Platinum",
        "Versa", "Versa S", "Versa SV", "Versa SR", "Versa Note",
        "X-Trail", "X-Trail Hybrid",
        "Frontier", "Frontier S", "Frontier SV", "Frontier Pro-4X", "Frontier King Cab", "Frontier Crew Cab",
        "Juke", "Juke NISMO", "Juke NISMO RS",
        "Patrol", "Patrol Y62", "Patrol Safari", "Patrol Nismo",
        "Murano", "Murano S", "Murano SV", "Murano SL", "Murano Platinum",
        "March", "March SR", "March Advance",
        "Navara", "Navara Pro-4X", "Navara Double Cab", "Navara King Cab",
        "Rogue", "Rogue S", "Rogue SV", "Rogue SL", "Rogue Sport", "Rogue Hybrid",
        "Maxima", "Maxima S", "Maxima SV", "Maxima SL", "Maxima SR", "Maxima Platinum",
        "Armada", "Armada SV", "Armada SL", "Armada Platinum",
        "Kicks", "Leaf", "GT-R", "Z", "370Z", "Pathfinder", "Qashqai", "Titan", "Terra"
    ],
    "Chevrolet": [
        "Aveo", "Aveo LT", "Aveo LS", "Aveo RS", "Aveo Sedan", "Aveo Hatchback",
        "Cruze", "Cruze LS", "Cruze LT", "Cruze Premier", "Cruze Hatchback", "Cruze Sedan",
        "Sonic", "Sonic LS", "Sonic LT", "Sonic RS", "Sonic Hatchback", "Sonic Sedan",
        "Malibu", "Malibu LS", "Malibu RS", "Malibu LT", "Malibu Premier", "Malibu Hybrid",
        "Spark", "Spark LS", "Spark LT", "Spark ACTIV",
        "Traverse", "Traverse LS", "Traverse LT", "Traverse RS", "Traverse Premier", "Traverse High Country",
        "Silverado", "Silverado 1500", "Silverado 2500HD", "Silverado 3500HD", "Silverado LT", "Silverado RST", "Silverado Custom", "Silverado Trail Boss",
        "Trailblazer", "Trailblazer LS", "Trailblazer LT", "Trailblazer ACTIV", "Trailblazer RS",
        "Equinox", "Equinox LS", "Equinox LT", "Equinox RS", "Equinox Premier",
        "Captiva", "Captiva Sport", "Captiva Premier",
        "Tahoe", "Tahoe LS", "Tahoe LT", "Tahoe RST", "Tahoe Z71", "Tahoe Premier", "Tahoe High Country",
        "Suburban", "Suburban LS", "Suburban LT", "Suburban RST", "Suburban Z71", "Suburban Premier", "Suburban High Country",
        "Blazer", "Blazer LT", "Blazer RS", "Blazer Premier",
        "Colorado", "Camaro", "Bolt", "Bolt EUV", "Onix", "Tracker", "Groove", "Orlando", "Corvette", "Joy", "Beat", "Cavalier", "Sail", "Traverse"
    ],
    "Ford": [
        "Fiesta", "Fiesta SE", "Fiesta ST", "Fiesta Titanium", "Fiesta Hatchback", "Fiesta Sedan",
        "Focus", "Focus SE", "Focus ST", "Focus RS", "Focus Titanium", "Focus Sedan", "Focus Hatchback", "Focus Electric",
        "Explorer", "Explorer XLT", "Explorer ST", "Explorer Limited", "Explorer Platinum", "Explorer Timberline", "Explorer Hybrid",
        "Escape", "Escape S", "Escape SE", "Escape SEL", "Escape Titanium", "Escape Hybrid", "Escape PHEV",
        "Mustang", "Mustang GT", "Mustang EcoBoost", "Mustang Mach-E", "Mustang Shelby GT500", "Mustang Shelby GT350", "Mustang Bullitt", "Mustang Mach 1",
        "F-150", "F-150 XL", "F-150 XLT", "F-150 Lariat", "F-150 King Ranch", "F-150 Platinum", "F-150 Limited", "F-150 Raptor", "F-150 Lightning", "F-150 Tremor", "F-150 Hybrid",
        "Ranger", "Ranger XL", "Ranger XLT", "Ranger Lariat", "Ranger Tremor", "Ranger Raptor",
        "Edge", "Edge SE", "Edge SEL", "Edge ST", "Edge Titanium",
        "EcoSport", "EcoSport S", "EcoSport SE", "EcoSport SES", "EcoSport Titanium",
        "Bronco", "Bronco Sport", "Bronco Big Bend", "Bronco Outer Banks", "Bronco Badlands", "Bronco Wildtrak", "Bronco Raptor",
        "Expedition", "Expedition XLT", "Expedition Limited", "Expedition King Ranch", "Expedition Platinum", "Expedition Timberline",
        "Maverick", "Maverick XL", "Maverick XLT", "Maverick Lariat", "Maverick Hybrid",
        "Transit", "Transit Connect", "Territory", "Tourneo", "Puma", "Super Duty", "Figo", "Ka", "Kuga", "Mondeo"
    ],
    "Hyundai": [
        "Elantra", "Elantra SE", "Elantra SEL", "Elantra Limited", "Elantra N Line", "Elantra N", "Elantra GT", "Elantra Hybrid",
        "Tucson", "Tucson SE", "Tucson SEL", "Tucson N Line", "Tucson Limited", "Tucson Hybrid", "Tucson Plug-in Hybrid",
        "Santa Fe", "Santa Fe SE", "Santa Fe SEL", "Santa Fe Limited", "Santa Fe Calligraphy", "Santa Fe XRT", "Santa Fe Hybrid", "Santa Fe Plug-in Hybrid",
        "Accent", "Accent SE", "Accent SEL", "Accent Limited",
        "Sonata", "Sonata SE", "Sonata SEL", "Sonata SEL Plus", "Sonata Limited", "Sonata N Line", "Sonata Hybrid",
        "Kona", "Kona SE", "Kona SEL", "Kona N Line", "Kona Limited", "Kona N", "Kona Electric",
        "Venue", "Venue SE", "Venue SEL", "Venue Limited", "Venue Denim",
        "Creta", "Creta Premium", "Creta Limited",
        "i10", "i10 SE", "i10 Premium", "i10 N Line",
        "i20", "i20 Essential", "i20 N", "i20 N Line",
        "Palisade", "Palisade SE", "Palisade SEL", "Palisade Limited", "Palisade Calligraphy",
        "Ioniq 5", "Ioniq 5 SE", "Ioniq 5 SEL", "Ioniq 5 Limited", "Ioniq 5 N",
        "Ioniq 6", "Ioniq 6 SE", "Ioniq 6 SEL", "Ioniq 6 Limited",
        "Veloster", "Veloster N", "Nexo", "Bayon", "Staria", "Azera", "Genesis", "Grandeur", "Ioniq Hybrid", "i30", "Custin"
    ],
    "Kia": [
        "Rio", "Rio LX", "Rio S", "Rio EX", "Rio GT-Line", "Rio Sedan", "Rio Hatchback",
        "Sportage", "Sportage LX", "Sportage EX", "Sportage SX", "Sportage X-Line", "Sportage Hybrid", "Sportage Plug-in Hybrid",
        "Sorento", "Sorento LX", "Sorento S", "Sorento EX", "Sorento SX", "Sorento X-Line", "Sorento Hybrid", "Sorento PHEV",
        "Soul", "Soul LX", "Soul S", "Soul GT-Line", "Soul EX", "Soul Turbo", "Soul EV",
        "Seltos", "Seltos LX", "Seltos S", "Seltos EX", "Seltos SX", "Seltos Nightfall",
        "Picanto", "Picanto GT-Line", "Picanto X-Line",
        "Cerato", "Cerato GT", "Cerato Sedan", "Cerato Hatchback",
        "Carnival", "Carnival LX", "Carnival EX", "Carnival SX", "Carnival SX Prestige",
        "Stinger", "Stinger GT-Line", "Stinger GT1", "Stinger GT2",
        "Optima", "Optima LX", "Optima S", "Optima EX", "Optima SX", "Optima Hybrid",
        "Telluride", "Telluride LX", "Telluride S", "Telluride EX", "Telluride SX", "Telluride X-Pro",
        "Niro", "Niro LX", "Niro EX", "Niro Touring", "Niro Hybrid", "Niro Plug-in Hybrid", "Niro EV",
        "EV6", "EV6 Light", "EV6 Wind", "EV6 GT-Line", "EV6 GT",
        "K5", "K5 LX", "K5 GT", "K5 GT-Line", "K5 EX", "Forte", "Cadenza", "Stonic", "Sonet", "K9", "K900", "Carens", "EV9"
    ],
    "Mazda": [
        "Mazda2", "Mazda2 Sport", "Mazda2 Touring", "Mazda2 Grand Touring",
        "Mazda3", "Mazda3 Sedan", "Mazda3 Hatchback", "Mazda3 Sport", "Mazda3 Touring", "Mazda3 Grand Touring", "Mazda3 Preferred", "Mazda3 Premium", "Mazda3 2.5 Turbo",
        "Mazda6", "Mazda6 Sport", "Mazda6 Touring", "Mazda6 Grand Touring", "Mazda6 Grand Touring Reserve", "Mazda6 Signature",
        "CX-3", "CX-3 Sport", "CX-3 Touring", "CX-3 Grand Touring",
        "CX-5", "CX-5 Sport", "CX-5 Touring", "CX-5 Carbon Edition", "CX-5 Grand Touring", "CX-5 Grand Touring Reserve", "CX-5 Signature", "CX-5 Turbo",
        "CX-30", "CX-30 Base", "CX-30 Select", "CX-30 Preferred", "CX-30 Premium", "CX-30 Turbo", "CX-30 Turbo Premium Plus",
        "CX-9", "CX-9 Sport", "CX-9 Touring", "CX-9 Carbon Edition", "CX-9 Grand Touring", "CX-9 Signature",
        "MX-5", "MX-5 Miata", "MX-5 RF", "MX-5 Sport", "MX-5 Club", "MX-5 Grand Touring",
        "BT-50", "BT-50 Thunder", "BT-50 XTR", "BT-50 GT",
        "CX-50", "CX-50 S", "CX-50 Preferred", "CX-50 Premium", "CX-50 Turbo", "CX-50 Meridian",
        "CX-90", "CX-90 Turbo", "CX-90 PHEV", "CX-90 Premium", "CX-90 Premium Plus", "CX-90 S", "CX-90 Signature",
        "CX-70", "CX-60", "MX-30", "RX-7", "RX-8"
    ],
    "Volkswagen": [
        "Golf", "Golf GTI", "Golf R", "e-Golf", "Golf SportWagen", "Golf Alltrack", "Golf TDI", "Golf TSI",
        "Jetta", "Jetta S", "Jetta SE", "Jetta R-Line", "Jetta SEL", "Jetta SEL Premium", "Jetta GLI", "Jetta TDI", "Jetta Hybrid",
        "Passat", "Passat S", "Passat SE", "Passat R-Line", "Passat SEL", "Passat TDI", "Passat GT",
        "Tiguan", "Tiguan S", "Tiguan SE", "Tiguan SEL", "Tiguan SEL Premium R-Line", "Tiguan R", "Tiguan TDI", "Tiguan AllSpace",
        "Polo", "Polo GTI", "Polo R-Line", "Polo Cross", "Polo Life", "Polo Style",
        "Touareg", "Touareg V6", "Touareg TDI", "Touareg Hybrid", "Touareg R", "Touareg Executive",
        "Beetle", "Beetle Turbo", "Beetle TDI", "Beetle Dune", "Beetle Convertible", "Beetle Classic", "Beetle Final Edition",
        "Amarok", "Amarok V6", "Amarok Comfortline", "Amarok Highline", "Amarok Aventura", "Amarok Dark Label",
        "Atlas", "Atlas SE", "Atlas SEL", "Atlas SEL Premium", "Atlas Cross Sport", "Atlas R-Line",
        "ID.4", "ID.4 Pro", "ID.4 Pro S", "ID.4 AWD Pro", "ID.4 AWD Pro S", "ID.4 GTX",
        "ID. Buzz", "ID. Buzz Cargo", "ID. Buzz Pro", "ID. Buzz Long Wheelbase",
        "Arteon", "Arteon SE", "Arteon SEL", "Arteon SEL Premium R-Line", "Taos", "T-Cross", "T-Roc", "Nivus", "Virtus", "ID.3", "Vento", "Saveiro", "Sharan", "Touran", "CC", "Phaeton"
    ],
    "Subaru": [
        "Impreza", "Impreza Sedan", "Impreza Hatchback", "Impreza Sport", "Impreza Limited", "Impreza WRX",
        "Forester", "Forester Base", "Forester Premium", "Forester Sport", "Forester Limited", "Forester Touring", "Forester Wilderness",
        "Outback", "Outback Base", "Outback Premium", "Outback Limited", "Outback Touring", "Outback Wilderness", "Outback XT", "Outback Onyx Edition",
        "Legacy", "Legacy Base", "Legacy Premium", "Legacy Sport", "Legacy Limited", "Legacy Limited XT", "Legacy Touring XT",
        "Crosstrek", "Crosstrek Base", "Crosstrek Premium", "Crosstrek Sport", "Crosstrek Limited", "Crosstrek Hybrid", "Crosstrek Wilderness",
        "WRX", "WRX Base", "WRX Premium", "WRX Limited", "WRX GT", "WRX STI", "WRX S209",
        "Ascent", "Ascent Base", "Ascent Premium", "Ascent Limited", "Ascent Touring", "Ascent Onyx Edition",
        "BRZ", "BRZ Premium", "BRZ Limited", "BRZ tS", "BRZ Series.Gray", "BRZ Series.White",
        "Solterra", "Solterra Premium", "Solterra Limited", "Solterra Touring",
        "XV", "Baja", "Tribeca", "Levorg", "SVX"
    ],
    "BMW": [
        "Serie 1", "128ti", "M135i", "120i", "116i", "Serie 1 Hatchback",
        "Serie 2", "220i", "M240i", "230i", "Serie 2 Coupe", "Serie 2 Gran Coupe", "Serie 2 Active Tourer", "Serie 2 Gran Tourer",
        "Serie 3", "320i", "330i", "340i", "330e", "M3", "M3 Competition", "Serie 3 Sedan", "Serie 3 Touring", "Serie 3 Gran Turismo",
        "Serie 4", "420i", "430i", "440i", "M4", "M4 Competition", "Serie 4 Coupe", "Serie 4 Convertible", "Serie 4 Gran Coupe",
        "Serie 5", "520i", "530i", "540i", "545e", "550i", "M5", "M5 Competition", "Serie 5 Sedan", "Serie 5 Touring", "Serie 5 Gran Turismo",
        "Serie 6", "630i", "640i", "650i", "M6", "Serie 6 Coupe", "Serie 6 Convertible", "Serie 6 Gran Coupe", "Serie 6 Gran Turismo",
        "Serie 7", "730i", "740i", "750i", "745e", "M760i", "Serie 7 Sedan", "Serie 7 Long Wheelbase",
        "Serie 8", "840i", "M850i", "M8", "M8 Competition", "Serie 8 Coupe", "Serie 8 Convertible", "Serie 8 Gran Coupe",
        "X1", "X1 sDrive18i", "X1 sDrive20i", "X1 xDrive20i", "X1 xDrive25e", "X1 M35i",
        "X2", "X2 sDrive18i", "X2 sDrive20i", "X2 xDrive20i", "X2 M35i",
        "X3", "X3 sDrive20i", "X3 xDrive20i", "X3 xDrive30i", "X3 M40i", "X3 M", "X3 M Competition",
        "X4", "X4 xDrive20i", "X4 xDrive30i", "X4 M40i", "X4 M", "X4 M Competition",
        "X5", "X5 xDrive40i", "X5 xDrive45e", "X5 M50i", "X5 M", "X5 M Competition",
        "X6", "X6 xDrive40i", "X6 M50i", "X6 M", "X6 M Competition",
        "X7", "X7 xDrive40i", "X7 M50i", "X7 M60i",
        "i3", "i3s", "i3 REx",
        "i4", "i4 eDrive35", "i4 eDrive40", "i4 M50",
        "i5", "i5 eDrive40", "i5 M60",
        "i7", "i7 xDrive60", "i7 M70",
        "iX", "iX xDrive40", "iX xDrive50", "iX M60",
        "Z4", "Z4 sDrive20i", "Z4 sDrive30i", "Z4 M40i",
        "XM", "iX1", "iX3", "i8", "M2", "X8", "M140i", "M550i", "M440i", "M340i"
    ],
    "Mercedes-Benz": [
        "Clase A", "A 180", "A 200", "A 250", "A 35 AMG", "A 45 AMG", "A-Class Sedan", "A-Class Hatchback",
        "Clase B", "B 180", "B 200", "B 250", "B-Class Electric Drive",
        "Clase C", "C 180", "C 200", "C 300", "C 43 AMG", "C 63 AMG", "C 63 AMG S", "C-Class Sedan", "C-Class Coupe", "C-Class Cabriolet", "C-Class Estate",
        "Clase E", "E 200", "E 300", "E 350", "E 400", "E 450", "E 53 AMG", "E 63 AMG", "E 63 AMG S", "E-Class Sedan", "E-Class Coupe", "E-Class Cabriolet", "E-Class Estate", "E-Class All-Terrain",
        "Clase S", "S 450", "S 500", "S 580", "S 580e", "S 63 AMG", "S 65 AMG", "S-Class Sedan", "S-Class Coupe", "S-Class Cabriolet",
        "CLA", "CLA 180", "CLA 200", "CLA 250", "CLA 35 AMG", "CLA 45 AMG", "CLA Coupe", "CLA Shooting Brake",
        "CLE", "CLE 300", "CLE 450", "CLE 53 AMG", "CLE Coupe", "CLE Cabriolet",
        "GLA", "GLA 200", "GLA 250", "GLA 35 AMG", "GLA 45 AMG",
        "GLB", "GLB 200", "GLB 250", "GLB 35 AMG",
        "GLC", "GLC 200", "GLC 300", "GLC 43 AMG", "GLC 63 AMG", "GLC Coupe", "GLC SUV",
        "GLE", "GLE 350", "GLE 450", "GLE 53 AMG", "GLE 63 AMG", "GLE Coupe", "GLE SUV",
        "GLS", "GLS 450", "GLS 580", "GLS 600 Maybach", "GLS 63 AMG",
        "G-Class", "G 550", "G 63 AMG", "G 65 AMG", "G-Wagon", "G-Class Professional",
        "EQA", "EQA 250", "EQA 300", "EQA 350",
        "EQB", "EQB 250", "EQB 300", "EQB 350",
        "EQE", "EQE 350", "EQE 500", "EQE 53 AMG", "EQE SUV", "EQE Sedan",
        "EQS", "EQS 450", "EQS 580", "EQS 53 AMG", "EQS SUV", "EQS Sedan",
        "AMG GT", "AMG GT 43", "AMG GT 53", "AMG GT 63", "AMG GT 63 S", "AMG GT 73", "AMG GT Coupe", "AMG GT Roadster", "AMG GT Black Series",
        "AMG SL", "AMG SL 43", "AMG SL 55", "AMG SL 63",
        "AMG ONE",
        "V-Class", "V 220", "V 250", "V 300", "Marco Polo",
        "Sprinter", "Sprinter Cargo", "Sprinter Passenger", "Sprinter Cab Chassis", "Sprinter Crew Van",
        "EQC", "EQV", "Citan", "Metris", "X-Class", "SL-Class", "SLC-Class", "R-Class", "Vito", "SLK-Class", "CLS-Class", "ML-Class"
    ],
    "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron GT", "RS e-tron GT"],
    "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Wagoneer", "Grand Wagoneer"],
    "Peugeot": ["208", "2008", "3008", "5008", "508", "308", "408", "607"],
    "Renault": ["Logan", "Sandero", "Duster", "Kwid", "Captur", "Clio", "Megane", "Talisman", "Arkana", "Austral"],
    "Fiat": ["500", "Panda", "Argo", "Cronos", "Mobi", "Tipo", "Uno", "Strada", "Pulse", "Fastback"],
    "Mitsubishi": ["Lancer", "Outlander", "ASX", "Montero", "Eclipse Cross", "Mirage", "Xpander", "Pajero Sport"],
    "Suzuki": ["Swift", "Vitara", "Baleno", "S-Cross", "Jimny", "Celerio", "Alto", "Ertiga", "Ignis", "XL7"],
    "Volvo": ["S60", "S90", "XC40", "XC60", "XC90", "V60", "V90", "EX30", "EX90"],
    "Tesla": [
        "Model S", "Model S Plaid", "Model S Long Range", "Model S Performance", "Model S Dual Motor", "Model S Tri Motor",
        "Model 3", "Model 3 Standard Range", "Model 3 Standard Range Plus", "Model 3 Long Range", "Model 3 Performance", "Model 3 RWD", "Model 3 AWD",
        "Model X", "Model X Plaid", "Model X Long Range", "Model X Performance", "Model X Dual Motor", "Model X Tri Motor",
        "Model Y", "Model Y Standard Range", "Model Y Long Range", "Model Y Performance", "Model Y RWD", "Model Y AWD",
        "Cybertruck", "Cybertruck Single Motor", "Cybertruck Dual Motor", "Cybertruck Tri Motor", "Cybertruck Foundation Series",
        "Roadster", "Roadster Sport", "Roadster SpaceX Package", "Roadster Founders Series",
        "Semi", "Semi Day Cab", "Semi Sleeper", "Semi Founders Series"
    ],
    "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar", "Freelander"],
    "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "F-Type", "I-Pace"],
    "Chery": ["Tiggo 2", "Tiggo 3", "Tiggo 5", "Tiggo 7", "Tiggo 8", "Tiggo 9", "Arrizo 5", "Arrizo 6", "Arrizo 8", "Omoda 5", "Omoda E5", "Tansuo 06"],
    "Geely": ["Coolray", "Azkarra", "Emgrand", "Okavango", "Panda", "Atlas", "Binrui", "Borui", "Geometry A", "Geometry C"],
    "BYD": ["Tang", "Han", "Dolphin", "Seal", "Yuan Plus", "Song Pro", "Qin Plus", "Seagull", "Destroyer 05", "Frigate 07"],
    "Great Wall": ["Wingle", "Haval H2", "Haval H6", "Poer", "Tank 300", "Haval Jolion", "Haval F7"],
    "MG": ["ZS", "HS", "MG3", "MG5", "RX5", "Marvel R", "MG6", "MG ZS EV"],
    "Isuzu": ["D-Max", "MU-X", "Trooper", "Rodeo", "N-Series", "F-Series"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Ram", "Hornet", "Neon"],
    "Ram": ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
    "Lexus": ["IS", "ES", "GS", "LS", "NX", "RX", "UX", "GX", "LX", "RC", "LC"],
    "Acura": ["ILX", "TLX", "RDX", "MDX", "NSX", "Integra", "ZDX"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
    "Mini": ["Cooper", "Clubman", "Countryman", "Paceman", "Electric", "John Cooper Works"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C", "MiTo", "8C Competizione"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "718 Cayman"],
    "Ferrari": ["488", "Roma", "Portofino", "SF90", "F8 Tributo", "296 GTB", "812 Superfast", "Purosangue"],
    "Lamborghini": ["Huracán", "Aventador", "Urus", "Revuelto", "Sián", "Gallardo"],
    "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
    "Rolls-Royce": ["Ghost", "Phantom", "Cullinan", "Wraith", "Dawn", "Spectre"],
    "Maserati": ["Ghibli", "Levante", "Quattroporte", "GranTurismo", "MC20", "Grecale"]
}
